[tool.poetry]
name = "hack-ip"
version = "2.0.0"
description = ""
authors = ["Subhomoy Roy Choudhury <subhomoyrchoudhury@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "hackip"}]

[tool.poetry.dependencies]
python = "^3.9"
rich = "^12.6.0"
requests = "^2.28.1"
setuptools = "^58.5.3"
psutil = "^5.9.0"
maxminddb-geolite2 = "^2018.703"
art = "^6.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
